# -*- coding: utf-8 -*-
"""TASK-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNT4mASA5K_9iWYEqfg8YFuGMNaCLQ00

CUSTOMER SEGMENTATION
"""

# ===============================================
# 🛍️ Customer Segmentation using K-Means Clustering
# ===============================================

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Step 1: Load Dataset
# Make sure your file is named 'customers.csv' or update the path below
df = pd.read_csv("/content/Mall_Customers.csv")

print("✅ Dataset Loaded Successfully!\n")
print(df.head(), "\n")

# Step 2: Select Features for Clustering
# We'll use Annual Income and Spending Score
X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

# Step 3: Feature Scaling (important for K-Means)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Step 4: Find the Optimal Number of Clusters (Elbow Method)
wcss = []  # Within-cluster sum of squares
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)


# Plot the Elbow curve
plt.figure(figsize=(8, 5))
plt.plot(range(1, 11), wcss, marker='o', color='b')
plt.title('Elbow Method - Optimal Number of Clusters')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('WCSS')
plt.show()

# Step 5: Choose the Optimal Number of Clusters (let's assume k=5)
kmeans = KMeans(n_clusters=5, init='k-means++', random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# Step 6: Visualize the Clusters
plt.figure(figsize=(8, 6))
plt.scatter(X_scaled[:, 0], X_scaled[:, 1], c=df['Cluster'], cmap='rainbow', s=60)
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1],
            s=200, c='black', marker='X', label='Centroids')
plt.title('Customer Segments based on Income & Spending')
plt.xlabel('Annual Income (scaled)')
plt.ylabel('Spending Score (scaled)')
plt.legend()
plt.show()

# Step 7: View Clustered Data
print("\n📊 Sample Clustered Data:")
print(df[['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
          'Spending Score (1-100)', 'Cluster']].head())

# Step 8 (Optional): Analyze Each Cluster
cluster_summary = df.groupby('Cluster')[['Annual Income (k$)', 'Spending Score (1-100)', 'Age']].mean()
print("\n🧩 Cluster Summary:")
print(cluster_summary)